name: archtech
type: drupal11
docroot: web
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: postgres
    version: "18"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: true
web_environment: []
web_extra_exposed_ports:
  - name: rabbitmq-mgmt
    container_port: 15672
    http_port: 15672
    https_port: 15673
  - name: grafana
    container_port: 3000
    http_port: 3000
    https_port: 3001
